---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.4

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@fa4f5b843fcc7c009e2d2cab4ff7a3481eff7473 # v1.14.0
