---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v2.3.4

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@b6feb003955cad286985c42e7047f4567a798f3f # v1.14.0
