---
name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  build:
    name: Build and test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.15, 1.14]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: -v go:build

      - name: Test
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: -v go:coverage

      - name: Send coverage
        uses: codecov/codecov-action@v1
        with:
          file: tests/coverage/coverage.out
